import { Inter } from "next/font/google";
import "../css/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="header">
          <h1>Profit-Calculator</h1>
        </header>
        <main className="main-content">{children}</main>
        <footer className="footer">
          <p>&copy; {new Date().getFullYear()} My App. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
